extends SceneTree

func _initialize() -> void:
	call_deferred("_run_tests")


func _run_tests() -> void:
	var adapter := InputAdapter.new()
	var diagonal := InputAdapter.normalized_movement(Vector2(1, 1), Vector2.ZERO)
	assert(is_equal_approx(diagonal.length(), 1.0), "diagonal must be normalized")
	assert(adapter.touch_press(3, Vector2(40, 300), Vector2(40, 300)))
	assert(not adapter.touch_press(4, Vector2(50, 300), Vector2(40, 300)))
	adapter.touch_drag(3, Vector2(100, 300))
	assert(adapter.movement().x > 0.99)
	adapter.touch_release(4)
	assert(adapter.movement().x > 0.99)
	adapter.touch_release(3)
	assert(adapter.movement() == Vector2.ZERO)
	adapter.touch_press(3, Vector2(40, 300), Vector2(40, 300))
	adapter.clear()
	assert(adapter.movement() == Vector2.ZERO)
	assert(adapter.touch_index == -1)
	Input.action_press("move_right")
	assert(adapter.movement().x > 0.99)
	Input.action_release("move_right")
	assert(adapter.movement() == Vector2.ZERO)
	var demo = load("res://scenes/Main.tscn").instantiate()
	root.add_child(demo)
	assert(demo.phase == "title")
	demo.start_or_restart()
	assert(demo.phase == "playing" and demo.state.tick == 0)
	Input.action_press("move_right")
	var old_position: Vector2 = demo.player
	demo._physics_process(1.0 / 60.0)
	assert(demo.player.distance_to(old_position) > 0.0)
	assert(demo.state.tick == 1)
	demo.notification(Node.NOTIFICATION_WM_WINDOW_FOCUS_OUT)
	assert(demo.phase == "paused")
	assert(demo.controls.movement() == Vector2.ZERO)
	var paused_position: Vector2 = demo.player
	demo._physics_process(1.0 / 60.0)
	assert(demo.player == paused_position and demo.state.tick == 1)
	demo.restart_demo()
	Input.action_press("move_right")
	demo.toggle_pause()
	assert(demo.phase == "paused" and demo.controls.movement() == Vector2.ZERO)
	demo.toggle_pause()
	assert(demo.phase == "playing" and demo.controls.movement() == Vector2.ZERO)
	demo.reset_demo()
	assert(demo.phase == "title" and demo.state.tick == 0)
	Input.action_release("move_right")
	print("[INPUT OK]")
	quit(0)
